clone:
  git:
    image: plugins/git
    depth: 1
    
pipeline:
  ansible:
    image: plugins/ansible
    settings:
      playbook: ansible.yml
      inventory: inventory
    branches: develop
  terraform_fmt:
    image: jmccann/drone-terraform:1
    settings:
      actions: 
        - fmt
      fmt_options:
        write: false
        diff: true
        check: true
  terraform_plan:
    image: jmccann/drone-terraform:1
    settings:
      actions:
        - validate
        - plan
    
   
