clone:
  git:
    image: plugins/git
    depth: 1
    when:
      status: [ success, failure ]
    
pipeline:
  build:
    image: devforth/drone-builder
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - /bin/bash build.sh
