clone:
  git:
    image: plugins/git
    depth: 2
    
pipeline:
  ansible:
    image: plugins/ansible
    settings:
      playbook: ansible.yml
      inventory: inventory
    when:
      branch: develop
  terraform_fmt:
    image: jmccann/drone-terraform:1
    settings:
      actions: 
        - fmt
        - validate
        - plan
      fmt_options:
        write: false
        diff: true
        check: true
    #when:
      #event: pull_request
    
   
