clone:
  git:
    image: plugins/git
    depth: 1
    
pipeline:
  ansible:
    image: plugins/ansible
    settings:
      playbook: ansible.yml
      inventory: inventory
    branches: [develop]
  terraform:
    image: jmccann/drone-terraform:1
    settings:
      plan: true
    
   
