clone:
  git:
    image: plugins/git:v1.2.0
    depth: 1
    
pipeline:
  build:
    image: devforth/drone-builder
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - ls
    when:
      status: [ success, failure ]
